## function include
library(tidyverse)
library(WriteXLS)
library(RJafroc)
source("sourcepgms/readworkstationfile.R")
source("sourcepgms/applyflowchart.R")
source("sourcepgms/makeJAFROCfile.R")
source("sourcepgms/derivesensspec.R")
source("sourcepgms/derivelesionsens.R")
source("sourcepgms/essentiallesions.R")
source("sourcepgms/derivedetections.R")
source("sourcepgms/plotPTC.R")
source("sourcepgms/plotDeltaFOM.R")
source("sourcepgms/plotFOM.R")
source("sourcepgms/prepareestimates.R")
source("sourcepgms/figuresave.R")
source("sourcepgms/plotthreshold_reader.R")
source("sourcepgms/plotthreshold_modality.R")
source("sourcepgms/plotPTCbins.R")

## Helper Functions
source("sourcepgms/binCI.R")
source("sourcepgms/getMaxConfidence.R")